DAST support for Website and Workflow Driven Scan Types.
fod-dev/fortify-on-demand-uploader-plugin pull request #118
Opened 2023-11-08 05:13 UTC by pvivekdev

Support for DAST Automated Scan from Fortify On Demand Plugin (Free Style Template).
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=888034
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=993003

Added Fod On Demand Dynamic Scan Post build plugin, 
Added Support DAST Scan types (Website, Workflow Driven).
Included Scope settings, Scan Type specific settings, Support to Create Application & Release for DAST. 
Included Network Auth/ Login Macro Setting to support Website/Workflow Driven. 
Included HTML File Type control to upload file into FOD API. 

### Testing done
1. Selection of Application and Release associated with current user.
2.  On selection of Fod On Demand Dynamic Post build action loads DAST UI controls. 
3. On selection of Scan type - Scan type specific UI controls are loaded. 
4. Saving the specific scan settings into DAST Fod API.
5. Loading the saved scan settings back into Jenkin UI controls on click on Jenkin Job - Save/Apply
6. Submitting Website and Workflow scan setting and initiate on click of Jenkin Job-  Build. 

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md 
You can override it by creating .github/pull_request_template.md in your own repository 
-->

2023-11-08 05:20 UTC, pvivekdev commented on src/main/java/org/jenkinsci/plugins/fodupload/DynamicAssessmentBuildStep.java
> +public class DynamicAssessmentBuildStep extends Recorder implements SimpleBuildStep {
Folder name -> DastFreeStyleBuildStep | DastPipelineBuildStep

2024-01-02 06:20 UTC, c0d3m0nky requested changes

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +                            if (host !== null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if (this.scanSettings !== undefined && this.scanSettings !== null) {
I'm perfectly fine with this way, it's more explicitly, but if you'd like to clean these if statements up by using truthiness it's perfectly safe to do...

if (this.scanSettings)

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if (this.scanSettings !== undefined && this.scanSettings.policy !== null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +            if (allowedHost !== undefined || null) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +            if (allowedHost !== undefined || null) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if (selectedApiTypeValue === null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if ((isVisible !== undefined || null)) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if (selectedApiTypeValue === null || undefined) {
to find any remaining you can use this regex in Edit > Find > Find in Files

(undefined|null) +\|\| +(undefined|null)

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +                case "openApi":
Use constant

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastFreeStyle.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +                            if (jq('#workflowMacroHosts').val() === null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +                        if (arr[index] !== undefined || null) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +                                if (host !== null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible !== undefined || null)) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if (selectedScanTypeValue === null || undefined) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +            if (allowedHost !== undefined || null) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +                case "openApi":
Use constant

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if ((isVisible === undefined || null) || isVisible === false) {
Also fix this if statement like I commented above

2024-01-02 06:20 UTC, c0d3m0nky commented on src/main/webapp/DastPipelineGenerator.js
> +        if (selectedApiTypeValue === null || undefined) {
Also fix this if statement like I commented above

2024-01-10 03:08 UTC, c0d3m0nky approved these changes

2024-03-04 16:43 UTC, merged